# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix product
#'
#' Standard matrix product. The first matrix must have as many columns as the
#' second has rows.
#'
#' @param MAT1 matrix
#' @param MAT2 matrix
#'
#' @author Ehouarn Le Faou
#'
MATRIX_PRODUCT <- function(MAT1, MAT2) {
    .Call(`_Ease_MATRIX_PRODUCT`, MAT1, MAT2)
}

#' Simulation of a metapopulation
#'
#' @param nbPop number of populations in the metapopulation
#' @param ids population IDs
#' @param migMat migration matrix
#' @param nsim number of simulations
#' @param verbose boolean determining if the progress of the simulations should be displayed or not (useful in case of many simulations)
#' @param recording a boolean indicating whether to record all mutations, i.e.
#' to record allelic and genotypic frequencies along the simulations
#' @param recordGenGap the number of generations between two records during
#' simulation, if the record parameter is TRUE. Whatever the value of this
#' parameter, both the first and the last generation will be included in
#' the record
#' @param drift a boolean indicating whether genetic drift should be
#' considered (i.e. whether deterministic simulations are performed or not)
#' @param nbHaplo number of haplotypes
#' @param nbGeno number of genotypes
#' @param idGeno genotypes ID
#' @param nbAlleles number of alleles for each loci
#' @param idAlleles alleles ID
#' @param nbLoci number of loci
#' @param initGenoFreq list of initial genotype frequencies in the populations
#' @param meiosisMat meiosis matrix
#' @param gametogenesisMat gametogenesis matrix
#' @param popSize list population sizes
#' @param threshold threshold for simulations
#' @param dioecy whether the population(s) is dioecious or not (hermaphrodism)
#' @param selfRate list of the selfing rate in populations (only for hermaphroditic population)
#' @param stopCondition list of stop conditions
#' @param IDstopCondition vector of stop condition ID
#' @param haploCrossMat haplotypes crossing matrix
#' @param alleleFreqMat matrix for calculating allelic frequencies
#' @param gamFit fitness of gametes
#' @param indFit fitness of individuals
#' @param gamProdFit fitness for gamete production
#' @param demography list of population demographies
#' @param growthRate list of population growth rates
#' @param initPopSize list of initial population
#' @param nameOutFunct name of the custom output function
#'
#' @author Ehouarn Le Faou
#'
METAPOP_SIMULATION <- function(nbPop, ids, migMat, nsim, verbose, recording, recordGenGap, drift, nbHaplo, nbGeno, idGeno, nbAlleles, idAlleles, nbLoci, initGenoFreq, meiosisMat, gametogenesisMat, popSize, threshold, dioecy, selfRate, stopCondition, IDstopCondition, haploCrossMat, alleleFreqMat, gamFit, indFit, gamProdFit, demography, growthRate, initPopSize, nameOutFunct) {
    .Call(`_Ease_METAPOP_SIMULATION`, nbPop, ids, migMat, nsim, verbose, recording, recordGenGap, drift, nbHaplo, nbGeno, idGeno, nbAlleles, idAlleles, nbLoci, initGenoFreq, meiosisMat, gametogenesisMat, popSize, threshold, dioecy, selfRate, stopCondition, IDstopCondition, haploCrossMat, alleleFreqMat, gamFit, indFit, gamProdFit, demography, growthRate, initPopSize, nameOutFunct)
}

